### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by JamesBremner** [besh81/nana-extra#1]
C:\Users\James\code\nana-extra\propertygrid\pgitems.cpp:12:10: fatal error: lock_guard.h: No such file or directory

**Comment by besh81** [comment]
propertygrid updated
Added missing file and a minimal demo

Thanks @JamesBremner

**Comment by JamesBremner** [comment]
Compilation successful.

Note: this widget now requires 7 files to be added to an application build.  I think it is a big selling point for potential users if you can say 'just add one header file and one cpp file' to your project.  Somewhere around 7 files and someone thinking of  using your code will say "too much trouble".  So I strongly suggest combining small header files ( like lock_guard.h ) with one of the larger header files.  I would also  urge you to consider combining all your header files and all your cpp files into one file for each.

**Comment by besh81** [comment]
I followed your suggestion. Now there are 4 files to include ... not 2 as hoped but better than 7 :)

**Comment by JamesBremner** [comment]
Excellent!  I will close this issue.

Suggestion:  Please use meaningful titles for your commits.  e.g. "merge source files"  Instead of titling all your commits "update".  It also helps if, when they are connected to an issue, you reference the issue ( number sign issue number ) so a link to the commit appears in the issue thread.
