### ISSUE TITLE
BUG in PropertyGrid: The property value is ONLY updated when the user presses the ENTER key

### ISSUE THREAD

**Issue by JamesBremner** [besh81/nana-extra#10]
i want to write the property values, after the user has set them, to a database.  But I do not get the new values set by the user.

This code ( based on demo with save button added )

```
#include <nana/gui.hpp>
#include <nana/gui/place.hpp>
#include <nana/gui/widgets/textbox.hpp>

#include "propertygrid.h"
#include "pgitems.h"

int main()
{
    nana::form fm(0, nana::size{ 600, 500 });
    nana::place pl{ fm };
    pl.div("margin=50 gap=5 field");

    nana::propertygrid propgrid{ fm };
    pl["field"] << propgrid;

    nana::textbox txt{ fm };
    pl["field"] << txt;
    txt.editable(false);


    // append category
    auto cat = propgrid.append("Standard properties");
    // append string property
    cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_string("string", "ABC")));
    // append int property
    cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_string_int("int", "-100")));
    // append unsigned int property
    cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_string_uint("unsigned int", "100")));
    // append string with button property
    cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_string_button("string + button", "Ciao")));
    // append choice property
    auto ip = cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_choice("choice")));
    auto pgchoiche = static_cast<nana::pg_choice*>(ip._m_pgitem());
    pgchoiche->push_back("One");
    pgchoiche->push_back("Two");
    pgchoiche->push_back("3");
    // append check property
    cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_check("check", true)));
    // append color property
    cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_color("color", "255,0,0")));
    // append color+inherited property
    ip = cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_color("color + inherited", "128,128,128", true)));
    ip.value("0,255,0");

    // connect the events
    propgrid.events().property_changed([&txt](const nana::arg_propertygrid& arg)
    {
        auto ip = arg.item;
        txt.append("[cat: " + std::to_string(ip.pos().cat) + ", pos: " + std::to_string(ip.pos().item) + "] ", true);
        txt.append("   label: " + ip.label() + "\n", true);
    });

    // Save button will read the current value of the int properrty
    nana::button save(fm,nana::rectangle{5,5,40,25},true);
    save.caption("SAVE");
    save.events().click([&propgrid]()
    {
        std::string t = propgrid.find("Standard properties","int").value();
        nana::msgbox msg("Current Value of int property");
        msg << t;
        msg.show();
    });


    pl.collocate();
    fm.show();
    nana::exec();
}
```

Shows this result after user changes int property to 34

![image](https://user-images.githubusercontent.com/2046227/54137349-e505fe80-43f3-11e9-8cd4-90f26504934e.png)

**Comment by JamesBremner** [comment]
I found this:

The property value is ONLY updated when the user presses the ENTER key

So, if the user types some new value in a property, but does not press the ENTER key instead simply clicking on somewhere else, then the display will show the new value, but it has not been captured by the program.

This is EXTREMELY CONFUSING.

I would say that when the property loses focus, then it should either capture the displayed value, or set the displayed value back to the real value.  My strong preference would be to capture the displayed value.

**Comment by JamesBremner** [comment]
I am wondering if we can update the property value in here:

https://github.com/besh81/nana-extra/blob/a032cdb82ec73bd12492bde2c839f8423b5d0f1b/propertygrid/propertygrid.cpp#L1012-L1021

**Comment by JamesBremner** [comment]
Found a fix.

Add this code to line 220 of pgitems.cpp

```C++
    txt_.events().focus([this](const nana::arg_focus& arg)
    {
        if( !arg.getting )
        {
            // just lost focus, so capture the value left by the user
            int int_val = std::stoi(txt_.caption());
            pg_string::value(std::to_string(int_val));
            emit_event();
        }
    });
```

**Comment by besh81** [comment]
You're right it was confusing!
Thanks for fixing it.
I'm going to add a flag where to specify the behavior on focus_lost: reload the old value or capture the new one.

**Comment by JamesBremner** [comment]
> I'm going to add a flag where to specify the behavior on focus_lost

Is it necessary?

If you think the user might ever want to reload the old value, maybe if the escape key is pressed the original value is loaded.

In my applications, I always have a button or menu item to reset everything ( every property ) back to the default values.

**Comment by JamesBremner** [comment]
Synced my fork and rebuilt my app from the master branch.  Everything looks good.  You can close this issue.
