### ISSUE TITLE
Question on PropertyGrid: Little box displayed beside every property

### ISSUE THREAD

**Issue by JamesBremner** [besh81/nana-extra#11]
![image](https://user-images.githubusercontent.com/2046227/54277517-772e1400-4566-11e9-8ac1-f16a875e7eeb.png)

What is the little box on the right of each property?  Why is it sometimes filled in?  What is it for?  How do I use it?

**Comment by besh81** [comment]
The idea is to have an additional set of options for each property (with each property I mean each class of property but could also be extended to each single property in the grid).
When clicking on the box a context menu appear. The default menu has only the reset entry (the menu of the color property has also the inherited entry).
Every single property has a default value that can be set.
The color of the box is empty if the property value is equal to the property default value. Is dark grey when the value is different from the default one.
The reset entry in the context menu needs to reset the value to the default one.

**Comment by JamesBremner** [comment]
Some nice features!  They should be documented somewhere!

What is it called?

How does one add to the items to the context menu?

Is there an option to hide the boxes if they are not used?

**Comment by JamesBremner** [comment]
Why not simply use a pop-up menu when user right clicks on the property?  Most users are accustomed to that behaviour.  It would be more economical with screen space.

( Motivation: my application is very complex with lots of graphs.  It is used in operating theaters where space is at a premium ( so no huge monitors ) and the doctors prefer the graphs to be as large as possible so they can be read without moving away from the patient.  The result is that the menus and any other widgets need to be as small as possible so as not to get in the way of the graphs.  This all means that I am always looking for places where I can save a pixel or two! )

**Comment by besh81** [comment]
I understand and could be a nice feature choose between the box and the right click.
I'll add to the todo list but don't expect this feature soon.
Thanks
Ciao

**Comment by JamesBremner** [comment]
Some unanswered questions from two days ago:

Documentation?

Name?

How to add items to the context menu?

Option to hide?

**Comment by besh81** [comment]
Hi,

sorry for the delay but in these days I'm very busy and the time for the hobbies is close to zero.

The name of the box is "interaction box". Inside the code is referred as ibox_
Unfortunately there's no docs and right now no way to hide it (hope to be able to work on this soon 7/10 days).

To add a new entry to the contect menu that popup clicking on the ibox check the implementation of pg_color class
	
	void pg_color::create(window wd)
	{
		// ibox context menu
		menu_.append_splitter();
		// 2. Inherited
		menu_.append("Inherited", [this](const nana::menu::item_proxy& ip)
		{
			pg_color::value(nana::to_string(color_, ip.checked()));
			printf(ip.checked() ? "[X]\n" : "[ ]\n");
			emit_event();
		});
		menu_.enabled(2, show_inherited_);
		menu_.check_style(2, nana::menu::checks::highlight);

		...
	}

Ciao
