### ISSUE TITLE
Feature Request PropertyGrid: Vertical gap between properties

### ISSUE THREAD

**Issue by JamesBremner** [besh81/nana-extra#12]
There is a generous vertical gap between properties.  Would it be possible to have an option to adjust the size of this gap, or even eliminate it entirely.

My application has over 100 properties, so there is a lot of scrolling when many categories are expanded.

Here is a screenshot of the app built with wxWidgets, which has no vertical gap between properties.

![image](https://user-images.githubusercontent.com/2046227/54277876-5d410100-4567-11e9-81ef-31d125aeecae.png)

**Comment by besh81** [comment]
Nana property grid doesn't have any lines between the properties that why I added more vertical space.
Anyway I will add this feature.
Thanks

**Comment by JamesBremner** [comment]
Great! 

I took a quick look at the code but could not see how to do it.

You should assign this issue to yourself.
