### ISSUE TITLE
PropertyGrid Question: Use of item_proxy::_m_pgitem()

### ISSUE THREAD

**Issue by JamesBremner** [besh81/nana-extra#9]
https://github.com/besh81/nana-extra/blob/a032cdb82ec73bd12492bde2c839f8423b5d0f1b/propertygrid/propertygrid.h#L259

The comment on the declaration of this method suggests it is for internal use only.

Yet I seem to need to use it very often in my application code.

Creating a choice property ( this is from your demo code )

	auto ip = cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_choice("choice")));
	auto pgchoiche = static_cast<nana::pg_choice*>(ip._m_pgitem());
	pgchoiche->push_back("One");
	pgchoiche->push_back("Two");
	pgchoiche->push_back("3");

and also when I need to select a choice

    int selected;
    ... set selected...
    (static_cast<nana::pg_choice*>(pg.find("Output Ports","A Format")._m_pgitem()))->option( selected ));

So, my questions:

 - Should I be using this, or something else?
 - If it should be used, can you fix the comment to describe what it does?
 - If it should be used, maybe you could change the name to make application code easier to read?

**Comment by JamesBremner** [comment]
I have added a method to simplify the setting of choice property options.

So, instead of

```
auto ip = cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_choice("choice")));
auto pgchoiche = static_cast<nana::pg_choice*>(ip._m_pgitem());
pgchoiche->push_back("One");
pgchoiche->push_back("Two");
pgchoiche->push_back("3");
```

we can write:

```
auto ip = cat.append(nana::propertygrid::pgitem_ptr(new nana::pg_choice("choice")));
ip.set({ "One", "Two", "3"  })
```

This is in PR #8

**Comment by besh81** [comment]
Great work! Now is cleaner, easier and faster.
Thanks
